# Aventar las notificaciones al iphone 
-  id: notificacion al empezar
   alias: 'NOTIFICAR IOS'
   hide_entity: False
   trigger: #lanzador
     - platform: homeassistant
       event: start
   condition: none
   action:
       service: notify.ios_rgb
       message: request_location_update
#       data:
#            message: "ALGO ESTÁ PASANDO"
#            data:
#                push:
#                    badge: 5
#            message: "ALGO ESTÁ PASANDO"
#            data:
#                subtitle: "subtitulo"

      
##SEND PUSH
-  id: push_llegandoacasa
   alias: Push llegando a casa
   hide_entity: false
   trigger:
     - platform: state
       entity_id: device_tracker.iphone
       to: 'home'
   action:
     - service: notify.ios_rgb
       data:
            push:
                badge: 5
                category: "GeoLights"
                
-  alias: check sensor value and show notification
   trigger:
       platform: numeric_state
       entity_id: sensor.random_sensor
       above: 10
   action:
       service: persistent_notification.create
       data:
           message: "sensor greather than 10"

           
-  alias: example automation
   trigger:
       platform: event
       event_type: CUSTOM_EVENT
   action:
     - service: input_select.select_option
       data:
           entity_id: input_select.who_cooks
           option: Palaus