- alias: example automation
  trigger:
    platform: event
    event_type: CUSTOM_EVENT
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.who_cooks
      option: Palaus
- id: Notificar_iphone
  alias: NOTIFICAR IPHONE
  trigger:
#    platform: homeassistant
#    event: start
    platform: zone
    entity_id: device_tracker.rgb
    zone: zone.home
    event: enter
  action:
    service: notify.ios_rgb
    data:
      message: "HOLA, YA SE DONDE ESTAS"
      data:
        push:
          badge: 5
          sound: default
          category: ALARM
- action:
  - data:
      message: "Sensor esta arriba de 10"
      title: "HAGAMOS PRUEBAS"
    service: persistent_notification.create
  alias: new_prueba
  id: '1498068178453'
  trigger:
  - above: '10'
    entity_id: sensor.random_sensor
    platform: numeric_state