homeassistant:
  # Name of the location where Home Assistant is running
  name: Homeraul
  # Location required to calculate the time the sun rises and sets
  latitude: 22.6464226
  longitude: -103.0205917
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2497
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Mexico_City
  
ios: #!include ios.conf
  push_categories: # Defines actionable notifications. Categories are groups of actions. You specify the category in the notification.
    - name: Alarm
      identifier: 'ALARM' # Must be unique and ALL CAPS
      actions:
        - identifier: 'SOUND_ALARM' # Must be unique and ALL CAPS
          title: 'Sound Alarm' # Needs to be short!
          activationMode: 'background' # or background. The mode in which to run the app when the action is performed.
          authenticationRequired: yes # A Boolean value indicating whether the user must unlock the device before the action is performed.
          destructive: yes # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
          behavior: 'default' # or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.
          context: 'default' # or Minimal. Default = In this context, the full UI is displayed for the notification’s alert. You may specify up to four custom actions in this context. Minimal = In this context, a minimal UI is displayed for the notification’s alert. You may specify up to two custom actions in this context.
        - identifier: 'SILENCE_ALARM' # Must be unique and ALL CAPS
          title: 'Silence Alarm' # Needs to be short!
          activationMode: 'background' # or background. The mode in which to run the app when the action is performed.
          authenticationRequired: yes # A Boolean value indicating whether the user must unlock the device before the action is performed.
          destructive: no # A Boolean value indicating whether the action is destructive.  When the value of this property is true, the system displays the corresponding button differently to indicate that the action is destructive.
          behavior: 'TextInput' # Default or TextInput. When TextInput the system provides a way for the user to enter a text response to be included with the notification.
          context: 'default' # or Minimal. Default = In this context, the full UI is displayed for the notification’s alert. You may specify up to four custom actions in this context. Minimal = In this context, a minimal UI is displayed for the notification’s alert. You may specify up to two custom actions in this context.
          textInputButtonTitle: 'Silencio!' # Only for iOS 10 when behavior is TextInput.
          textInputPlaceholder: '...' # Only for iOS 10 when behavior is TextInput.
          parameters: # iOS 9 only. Use this dictionary to specify any behavior-specific data for the action. For example, if you set behavior to TextInput you can use the UIUserNotificationTextInputActionButtonTitleKey key, which lets you customize the title of the button displayed by the text input interface.
            UIUserNotificationTextInputActionButtonTitleKey: "Silencio!"


# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  #api_password: 2017
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:


# Discover some devices automatically
#discovery: enabled

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
#sun:

# Weather Prediction
#sensor:
#  platform: yr

# Text to speech
tts:
  platform: google


zone 1:
  name: Casa
  latitude: 22.773201
  longitude: -102.544900
  track_ios: true
  icon: mdi:castle
  
zone 2:
  name: Centro
  latitude: 22.7747805
  longitude: -102.5770593
  track_ios: true
  icon: mdi:car
  
device_tracker:
#  - platform: icloud
#    track_new_devices: true
#    consider_home: 00:03:00
#    username: <USERNAME>
#    password: <PASSWORD>
  #- platform: owntracks
    #max_gps_accuracy: 200
    #waypoints: True
    #waypoint_whitelist:
    #    - jon
    #    - ram
#  - platform: iphone

#notify:
#  - platform: ios
notify:
  - name: notificar
    platform: ios
    #target: 968d4258-a7f7-3864-afee-cff02518b1dd

sensor:
#    platform: random
#    name: Mi número aleatorio
    #minimum: 1
    #maximum: 10
#    unit_of_measurement: trochiles
#action:
#    service: notify.ios_rgb
#    data:
#        message: 'algo'

    
#group: !include groups.yaml
automation: !include automations.yaml

input_select:
    who_cooks:
        name: Who cooks today
        options:
         - Palaus
         - Anne
        initial: Anne
        icon: mdi:panda
    living_room_preset:
        options:
         - visitors
         - visitors with kids
         - home alone