homeassistant:
  # Name of the location where Home Assistant is running
  name: Homeraul
  # Location required to calculate the time the sun rises and sets
  latitude: 22.9302551
  longitude: -102.6863254
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2497
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Mexico_City
  
ios: #!include ios.conf
  push:
    categories:
      - name: geolights
        identifier: 'GeoLights'
        actions:
          - identifier: 'lights_on'
            title: 'Switch Lights on'
            activationMode: 'background'
            authenticationRequired: yes
            destructive: yes
            behavior: 'default'
#    health_check: true
#    push_categories:
#      - name: Generic
#        identifier: 'GENERIC'
#    push:
#        categories:
#          - name: Alarm
#            identifier: 'ALARM'
#            actions:
#              - identifier: 'Sound_alarm'
#                title: 'Sonar alarma'
#                 activationMode: 'background'
#                 authenticationRequired: yes
#                 behavior: 'default'
# Show links to resources in log and frontend
introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  #api_password: 2017
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:


# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Weather Prediction
#sensor:
#  platform: yr

# Text to speech
tts:
  platform: google


zone 1:
  name: Casa
  latitude: 22.9302551
  longitude: -102.6863254
  radius: 10
  track_ios: true
  icon: mdi:castle
  
device_tracker:
  - platform: icloud
    username: raulcgon
    password: '#$R.carlos10'
    
  #- platform: owntracks
    #max_gps_accuracy: 200
    #waypoints: True
    #waypoint_whitelist:
    #    - jon
    #    - ram
#  - platform: iphone

#notify:
#  - platform: ios
notify:

#action:
#    service: notify.ios_rgb
#    data:
#        message: 'algo'

    
group: !include groups.yaml
automation: !include automations.yaml